"""
配置文件示例
可根据需要修改默认参数
"""

# 画布默认尺寸
CANVAS_WIDTH = 600
CANVAS_HEIGHT = 600
CANVAS_BG_COLOR = (0, 0, 0)  # 黑色背景
# CANVAS_BG_COLOR = (255, 255, 255)  # 白色背景

# 笔刷默认大小
DEFAULT_BRUSH_SIZE = 3
DEFAULT_BRUSH_COLOR = (255, 255, 255)  # 白色笔刷
# DEFAULT_BRUSH_COLOR = (0, 0, 0)  # 黑色笔刷

# 形态学操作默认参数
DEFAULT_KERNEL_SIZE = 5

# Canny边缘检测默认参数
DEFAULT_CANNY_THRESHOLD1 = 0
DEFAULT_CANNY_THRESHOLD2 = 255

# 日志栏高度
STATS_PANEL_HEIGHT = 300

# 窗口大小
MAIN_WINDOW_WIDTH = CANVAS_WIDTH*2 + 200
MAIN_WINDOW_HEIGHT = CANVAS_HEIGHT

# 应用标题
APP_TITLE = "OpenCV算子预览工具"
